name: ${artifactId}
main: ${groupId}.${artifactId}
version: ${version}

depend: [HolographicDisplays, MultiWorld, ProtocolLib]

commands:
  bw:
    description: BedWars plugin
    usage: /<command> help